"""
report_generator.py

SAFE xhtml2pdf-compatible PDF generator.
No advanced CSS. No frames. No corruption.
"""

import os
import datetime
import markdown
from xhtml2pdf import pisa
from jinja2 import Environment, BaseLoader

# SAFE TEMPLATE

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
body {
  font-family: Helvetica, Arial, sans-serif;
  font-size: 10pt;
  color: #222222;
  line-height: 1.5;
}

h1 {
  font-size: 16pt;
  border-bottom: 2px solid #cc0000;
  padding-bottom: 4pt;
}

h2 {
  font-size: 12pt;
  color: #cc0000;
  margin-top: 16pt;
}

h3 {
  font-size: 10.5pt;
  margin-top: 12pt;
}

p {
  margin-bottom: 8pt;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin: 10pt 0;
  font-size: 9pt;
}

th {
  background-color: #333333;
  color: white;
  padding: 6pt;
  text-align: left;
}

td {
  padding: 6pt;
  border-bottom: 1px solid #dddddd;
}

tr:nth-child(even) td {
  background-color: #f5f5f5;
}

.cover {
  text-align: center;
  padding: 60pt 20pt;
  page-break-after: always;
}

.cover h1 {
  font-size: 28pt;
  border: none;
}

.meta {
  margin-top: 20pt;
  font-size: 9pt;
  color: #666666;
}

.box {
  border: 1px solid #cccccc;
  padding: 8pt;
  margin: 10pt 0;
  background-color: #f9f9f9;
}

.footer {
  margin-top: 30pt;
  font-size: 8pt;
  color: #888888;
  text-align: center;
}
</style>
</head>

<body>

<div class="cover">
  <h1>{{ product_name }}</h1>
  <p>Market Intelligence Report</p>

  <div class="meta">
    <p><b>Date:</b> {{ current_date }}</p>
    <p><b>Reviews Analysed:</b> {{ review_count }}</p>
    <p><b>Sentiment Score:</b> {{ sentiment_score }}</p>
  </div>
</div>

<div class="box">
  <b>Methodology</b><br/>
  {{ methodology }}
</div>

{{ body_html }}

<h1>Appendix — Reviews</h1>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Source</th>
      <th>Sentiment</th>
      <th>Text</th>
    </tr>
  </thead>
  <tbody>
  {% for r in reviews %}
    <tr>
      <td>{{ loop.index }}</td>
      <td>{{ r.get("source", "unknown") }}</td>
      <td>{{ r.get("sentiment", "neutral") }}</td>
      <td>{{ r.get("text", "") }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

<div class="footer">
  Generated by Product Intelligence Engine
</div>

</body>
</html>
"""
# PDF CONVERSION

def convert_to_pdf(
    markdown_text: str,
    output_path: str,
    reviews: list,
    chart_paths: list = None,
    product_name: str = "Product",
    analysis_result: dict = None,
) -> bool:

    print(f"[PDF] Rendering → {output_path}")

    body_html = markdown.markdown(
        markdown_text or "",
        extensions=["extra", "tables", "nl2br"],
    )

    sentiment_data = (analysis_result or {}).get("sentiment", {})
    sentiment_score = sentiment_data.get("sentiment_score", "N/A")
    methodology = sentiment_data.get(
        "methodology",
        "Weighted Compound Score (WCS) sentiment analysis."
    )

    env = Environment(loader=BaseLoader(), autoescape=False)
    template = env.from_string(REPORT_TEMPLATE)

    html = template.render(
        product_name=product_name,
        current_date=datetime.date.today().isoformat(),
        body_html=body_html,
        reviews=reviews or [],
        review_count=len(reviews or []),
        sentiment_score=sentiment_score,
        methodology=methodology,
    )

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    try:
        with open(output_path, "wb") as f:
            result = pisa.CreatePDF(html, dest=f)

        if result.err:
            print("[PDF] xhtml2pdf reported errors")
            return False

        print("[PDF] SUCCESS")
        return True

    except Exception as e:
        print("[PDF] FAILED:", e)
        return False